--- #YAML:1.0
name:               Bio-Homology-InterologWalk
version:            0.06
abstract:           Retrieve, score and visualize putative Protein-Protein Interactions through the orthology-walk method
author:
    - Giuseppe Gallone <ggallone@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    File::Glob:    0
    Getopt::Long:  0
    List::Util:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
